name: CI

on:
  pull_request:
    branches: [main, develop]
jobs:
  client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: yarn
      - name: install
        run: yarn --frozen-lockfile

      - name: lint
        run: yarn lint:eslint
      - name: format
        run: yarn lint:prettier
      - name: jest
        run: yarn test
      - name: build test
        run: yarn build
